name: Docker

on:
  push:
    branches: [ "mundose" ]
  pull_request:
    branches: [ "mundose" ]

env:
  REGISTRY: roxsross12
  REPOSITORY: challenge-docker

jobs:
  docker-build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        run: |
          DIR=/home/runner/work/challenge-docker/challenge-docker
          cd $DIR/src
          ls
          #docker build -t $REGISTRY/$REPOSITORY:1.0.0-app .
          #docker push $REGISTRY/$REPOSITORY:1.0.0-app

      
